# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: uas_aris
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  analyzer: ^6.4.1
  intl: ^0.19.0
  nylo_framework: ^5.30.0
  pretty_dio_logger: ^1.3.1
  ndialog: ^4.3.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.1
  dio: ^5.4.3+1
  flutter_smart_dialog: ^4.9.7+7
  double_back_to_close_app: ^2.1.0
  dropdown_button2: ^2.3.9
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  fl_chart: ^0.68.0
  jwt_decoder: ^2.0.1
  pull_to_refresh_flutter3: ^2.0.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
#  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# APP ICON - public/assets/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/assets/app_icon/icon.png"
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
